# Generated by Django 5.2.6 on 2025-10-13 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10, verbose_name='Mois')),
                ('hours_of_absence', models.CharField(blank=True, max_length=63, null=True, verbose_name="Heures d'absence")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Presence',
                'verbose_name_plural': 'Presences',
                'ordering': ['created'],
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PrecenceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('state', models.CharField(choices=[('ENTREE', 'Entree'), (' SORTIE', 'Sortie')], default='ENTREE', max_length=10, verbose_name='Etat')),
                ('times', models.TimeField(verbose_name='Heure')),
                ('identifier', models.CharField(max_length=100, verbose_name='Identifiant')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pointing.presence', verbose_name='Presence')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
