# Generated by Django 5.2.6 on 2025-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='hours_of_absence',
            new_name='total_hours_of_absence',
        ),
        migrations.AddField(
            model_name='presence',
            name='details',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='presence',
            name='total_debts',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Heures dettes'),
        ),
        migrations.AddField(
            model_name='presence',
            name='total_overtime',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Heures sup'),
        ),
    ]
