# Generated by Django 5.2.6 on 2025-10-16 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0002_rename_hours_of_absence_presence_total_hours_of_absence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='precenceitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence_items', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
