# Generated by Django 5.2.6 on 2025-10-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0003_precenceitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precenceitem',
            name='state',
            field=models.CharField(choices=[('ENTREE', 'Entree'), ('SORTIE', 'Sortie')], default='ENTREE', max_length=10, verbose_name='Etat'),
        ),
    ]
