# Generated by Django 5.2.6 on 2025-10-06 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du rapport')),
                ('type', models.CharField(choices=[('RQ', 'Rapport Quotidien'), ('RH', 'Rapport Hebdomadaire'), ('JRA', 'Justificatif'), ('QUIZ', 'Evaluation')], default='RQ', max_length=5, verbose_name='Type de rapport')),
                ('published', models.BooleanField(default=False)),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Date de debut')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('marks', models.PositiveBigIntegerField(default=0, verbose_name='Note')),
                ('responsible_comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('employee_comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Nom de la tache')),
                ('is_completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='reporting.report', verbose_name='Rapport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tache',
                'verbose_name_plural': 'Taches',
                'ordering': ['created'],
            },
        ),
    ]
