# Generated by Django 5.2.6 on 2025-11-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaires administrateur'),
        ),
        migrations.AddField(
            model_name='report',
            name='admin_marks',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Note administrateur'),
        ),
    ]
