# Generated by Django 5.2.6 on 2025-11-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_report_admin_marks_user_report_marks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=1500, verbose_name='Nom de la tache'),
        ),
    ]
