# Generated by Django 5.2.6 on 2025-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifiant'),
        ),
    ]
