# Generated by Django 5.2.6 on 2025-10-21 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_company'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV')),
                ('gender', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], default='male', max_length=10, verbose_name='Genre')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titre de poste')),
                ('job_file', models.FileField(blank=True, null=True, upload_to='job_files/', verbose_name='Fiche de poste')),
                ('cni', models.FileField(blank=True, null=True, upload_to='cnis/', verbose_name='CNI')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Salaire')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['created'],
            },
        ),
    ]
