# Generated by Django 5.2.6 on 2025-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Adresse email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compagnie',
                'verbose_name_plural': 'Compagnies',
                'ordering': ['name'],
            },
        ),
    ]
